Validations
karilint/rnames pull request #42
Opened 2021-11-07 12:18 UTC by qubelka

- Make on frontend the same checks as when creating a Reference model
- Prevent from submitting form without snames / references
- Do not update ref id on the sname (all snames will be connected to the one reference)

2021-11-07 13:31 UTC, tonimobin commented
Everything seems to work, but an additional - more thorough review probably wouldn't hurt. Left a small question regarding doi's in slack.

2021-11-08 11:49 UTC, chzesa requested changes

2021-11-08 11:49 UTC, chzesa commented on app/frontend/src/components/Submit.js
> +		if (data.structured_names.length === 0 || data.relations.length === 0) {
Having no added structured names is probably a valid scenario if all new relations are between existing names.

2021-11-08 11:49 UTC, chzesa commented on app/frontend/src/validations.js
> +				if (!yearAsNumber) {
The first conditional can be dropped if `yearAsNumber` is compared to NaN

2021-11-08 11:49 UTC, chzesa commented on app/frontend/src/validations.js
> +	}
Year must be an integer to pass validation on server.

2021-11-08 18:03 UTC, chzesa approved these changes

2021-11-08 18:07 UTC, merged